Repository MisoRobotics/usb_cam, pull requests merged in 2021-09, with the labels that each got.

#11 SFS-2413: Add power_line_frequency paramater to usb paramaters
  nodes/usb_cam_node.cpp
Labels: enhancement

#12 SFS-2431: Add gamma parameter to usb parameters
  nodes/usb_cam_node.cpp
Labels: bug

#13 release/0.5.0
  CHANGELOG.rst
  nodes/usb_cam_node.cpp
  package.xml
Labels: release

#14 Merge master back into develop
  CHANGELOG.rst
  nodes/usb_cam_node.cpp
  package.xml
Labels: release

#15 SFS-2543: Add backlight_compensation parameter to usb parameters
  nodes/usb_cam_node.cpp
Labels: enhancement

#10 CRS-782: Add ROS parameter for tuning MJPEG video streaming
  include/usb_cam/usb_cam.h
  nodes/usb_cam_node.cpp
  src/usb_cam.cpp
Labels: enhancement, ready to merge
