Repository MisoRobotics/usb_cam, pull requests merged in 2022-05, with the labels that each got.

#31 SFS-3757: Add frequency monitoring for USB_Cam Node
  nodes/usb_cam_node.cpp
Labels: flippy

#34 SFS-7493: Fix not properly handling camera device with null serial
  src/device_utils.cpp
Labels: bug, flippy

#35 Release 0.7.2 for flippy
  CHANGELOG.rst
  package.xml
  src/device_utils.cpp
Labels: release, flippy

#36 Backmerge master into develop for flippy-0.7.2
  CHANGELOG.rst
  package.xml
  src/device_utils.cpp
Labels: release, flippy
