Repository MisoRobotics/usb_cam, pull requests merged in 2022-10, with the labels that each got.

#47 Release 0.8.2 for flippy
  CHANGELOG.rst
  include/usb_cam/usb_cam.h
  nodes/usb_cam_node.cpp
  package.xml
  src/usb_cam.cpp
Labels: release, flippy

#46 FSIT-3393: Add auto reset exposure setting
  launch/usb_cam-test.launch
  nodes/usb_cam_node.cpp
Labels: flippy

#49 Release 0.8.3 for flippy
  CHANGELOG.rst
  launch/usb_cam-test.launch
  nodes/usb_cam_node.cpp
  package.xml
Labels: release, flippy

#50 Backmerge master into develop for flippy-0.8.3
  CHANGELOG.rst
  package.xml
Labels: release, flippy

#45 SFS-8564, SFS-10034: Add new freq monitoring and diagnostic launch files
  CMakeLists.txt
  nodes/usb_cam_node.cpp
  package.xml
Labels: flippy

#51 FSIT-3680: Fix autobin auto reset exposure setting
  include/usb_cam/usb_cam.h
  nodes/usb_cam_node.cpp
  src/usb_cam.cpp
Labels: bug, flippy
