Repository MisoRobotics/usb_cam, pull requests merged in 2024-07, with the labels that each got.

#57 F3-2084: Update USB cam param name
  nodes/usb_cam_node.cpp
Labels: bug, flippy

#60 Release 1.0.1 for flippy-3.0.5-noetic
  CHANGELOG.rst
  nodes/usb_cam_node.cpp
  package.xml
Labels: release, flippy

#61 Backmerge 1.0.1 into develop for flippy-3.0.5-noetic
  CHANGELOG.rst
  package.xml
Labels: release, flippy

#62 F3-5443: Add pause before setting the exposure level
  nodes/usb_cam_node.cpp
  src/usb_cam.cpp
Labels: enhancement, flippy

#64 F3-5443: Add service for resetting the camera exposure
  nodes/usb_cam_node.cpp
Labels: enhancement, flippy

#65 F3-5443: Block manual cycle after init cycle
  nodes/usb_cam_node.cpp
Labels: bug, flippy

#66 Release 1.0.2 for flippy-3.0.6-noetic
  CHANGELOG.rst
  nodes/usb_cam_node.cpp
  package.xml
  src/usb_cam.cpp
Labels: release, flippy

#67 Backmerge 1.0.2 into develop for flippy-3.0.6-noetic
  CHANGELOG.rst
  package.xml
Labels: release, flippy
